### ISSUE TITLE
How do i run in It on mac

### ISSUE THREAD

**Issue by Joshua56** [msalmankhaliq/YOLO-Object-detection-using-OpenCv#1]
Hello 
I am trying to run it but i am getting some errors even if i have yolov3.weights
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-12-0cb730724c72> in <module>
      1 # load the COCO class labels our YOLO model was trained on
      2 labelspath = os.path.sep.join([yolo_dir, "coco.names"])
----> 3 labels = open(labelspath).read().strip().split("\n")

FileNotFoundError: [Errno 2] No such file or directory: 'yolo-coco/coco.names'

**Comment by msalmankhaliq** [comment]
Hello,
There is a label file in the coco folder named "coco.names". You need to place this file on the same directory and load it on your notebook.

**Comment by Joshua56** [comment]
[
![Screenshot 2020-06-04 at 23 46 11](https://user-images.githubusercontent.com/25225149/83808573-aece3200-a6bd-11ea-8ef5-a96ccc28f57c.png)
](url)

**Comment by Joshua56** [comment]
Hey Msalmankhaliq/Yolo-Object-Detection-Using-Opencv kindly share your
email address or whatsapp number i want you to help me with this error

**Comment by msalmankhaliq** [comment]
I have seen the screen shot that you send me. You need to to make few minor changes. Change the code into this, it will solve your error I believe.

`yolo_dir = os.path.join("coco")`


Also, place your yolov3 weights file inside coco folder.
my email: m.salmankhaliq7@gmail.com
